FROM xnaveira/rostollador_builder

RUN mkdir -p rostollador
WORKDIR /rostollador/
ADD ./*.py /rostollador/
ADD handlers /rostollador/handlers/
ADD version /rostollador/
RUN cd /rostollador/ && python -m unittest -v
